# #_threads=0  trace_file  dir
0 /home/cumulus/mcsim/TraceGen/pipes-classic/out0 /home/cumulus/mcsim/McSim/hello HELLO
0 /home/cumulus/mcsim/TraceGen/pipes-classic/out1 /home/cumulus/mcsim/McSim/hello HELLO
0 /home/cumulus/mcsim/TraceGen/pipes-classic/out2 /home/cumulus/mcsim/McSim/hello HELLO
0 /home/cumulus/mcsim/TraceGen/pipes-classic/out3 /home/cumulus/mcsim/McSim/hello HELLO
0 /home/cumulus/mcsim/TraceGen/pipes-classic/out4 /home/cumulus/mcsim/McSim/hello HELLO
0 /home/cumulus/mcsim/TraceGen/pipes-classic/out5 /home/cumulus/mcsim/McSim/hello HELLO
0 /home/cumulus/mcsim/TraceGen/pipes-classic/out6 /home/cumulus/mcsim/McSim/hello HELLO
0 /home/cumulus/mcsim/TraceGen/pipes-classic/out7 /home/cumulus/mcsim/McSim/hello HELLO
0 /home/cumulus/mcsim/TraceGen/pipes-classic/out8 /home/cumulus/mcsim/McSim/hello HELLO
0 /home/cumulus/mcsim/TraceGen/pipes-classic/out9 /home/cumulus/mcsim/McSim/hello HELLO
