# #_threads=0  trace_file  dir
0 /home/armel/mcsim/TraceGen/mcf.trace/mcf.20754.trace /home/armel/mcsim/McSim/hello HELLO
0 /home/armel/mcsim/TraceGen/mcf.trace/mcf.20754.trace /home/armel/mcsim/McSim/hello HELLO
0 /home/armel/mcsim/TraceGen/mcf.trace/mcf.20754.trace /home/armel/mcsim/McSim/hello HELLO
0 /home/armel/mcsim/TraceGen/mcf.trace/mcf.20754.trace /home/armel/mcsim/McSim/hello HELLO
0 /home/armel/mcsim/TraceGen/mcf.trace/mcf.20754.trace /home/armel/mcsim/McSim/hello HELLO
0 /home/armel/mcsim/TraceGen/mcf.trace/mcf.20754.trace /home/armel/mcsim/McSim/hello HELLO
0 /home/armel/mcsim/TraceGen/mcf.trace/mcf.20754.trace /home/armel/mcsim/McSim/hello HELLO
0 /home/armel/mcsim/TraceGen/mcf.trace/mcf.20754.trace /home/armel/mcsim/McSim/hello HELLO
0 /home/armel/mcsim/TraceGen/mcf.trace/mcf.20754.trace /home/armel/mcsim/McSim/hello HELLO
0 /home/armel/mcsim/TraceGen/mcf.trace/mcf.20754.trace /home/armel/mcsim/McSim/hello HELLO
0 /home/armel/mcsim/TraceGen/mcf.trace/mcf.20754.trace /home/armel/mcsim/McSim/hello HELLO
0 /home/armel/mcsim/TraceGen/mcf.trace/mcf.20754.trace /home/armel/mcsim/McSim/hello HELLO
