# #_threads=0  trace_file  dir
0 /home/armel/mcsim/TraceGen/python_wordcount.trace/python_wordcount.154963.trace /home/armel/mcsim/McSim/hello HELLO
0 /home/armel/mcsim/TraceGen/python_wordcount.trace/python_wordcount.154963.trace /home/armel/mcsim/McSim/hello HELLO
0 /home/armel/mcsim/TraceGen/python_wordcount.trace/python_wordcount.154963.trace /home/armel/mcsim/McSim/hello HELLO
0 /home/armel/mcsim/TraceGen/python_wordcount.trace/python_wordcount.154963.trace /home/armel/mcsim/McSim/hello HELLO
0 /home/armel/mcsim/TraceGen/python_wordcount.trace/python_wordcount.154963.trace /home/armel/mcsim/McSim/hello HELLO
0 /home/armel/mcsim/TraceGen/python_wordcount.trace/python_wordcount.154963.trace /home/armel/mcsim/McSim/hello HELLO
0 /home/armel/mcsim/TraceGen/python_wordcount.trace/python_wordcount.154963.trace /home/armel/mcsim/McSim/hello HELLO
0 /home/armel/mcsim/TraceGen/python_wordcount.trace/python_wordcount.154963.trace /home/armel/mcsim/McSim/hello HELLO
#0 /home/armel/mcsim/TraceGen/noisy.trace/noisy.120807.trace /home/armel/mcsim/McSim/hello HELLO
