# #_threads=0  trace_file  dir
0 /home/cumulus/mcsim/TraceGen/pipes-1-16/out0 /home/cumulus/mcsim/McSim/hello HELLO
0 /home/cumulus/mcsim/TraceGen/pipes-1-16/out1 /home/cumulus/mcsim/McSim/hello HELLO
0 /home/cumulus/mcsim/TraceGen/pipes-1-16/out2 /home/cumulus/mcsim/McSim/hello HELLO
0 /home/cumulus/mcsim/TraceGen/pipes-1-16/out3 /home/cumulus/mcsim/McSim/hello HELLO
0 /home/cumulus/mcsim/TraceGen/pipes-1-16/out4 /home/cumulus/mcsim/McSim/hello HELLO
0 /home/cumulus/mcsim/TraceGen/pipes-1-16/out5 /home/cumulus/mcsim/McSim/hello HELLO
0 /home/cumulus/mcsim/TraceGen/pipes-1-16/out6 /home/cumulus/mcsim/McSim/hello HELLO
0 /home/cumulus/mcsim/TraceGen/pipes-1-16/out7 /home/cumulus/mcsim/McSim/hello HELLO
#0 /home/cumulus/mcsim/TraceGen/pipes-1-16/out8 /home/cumulus/mcsim/McSim/hello HELLO
#0 /home/cumulus/mcsim/TraceGen/pipes-1-16/out9 /home/cumulus/mcsim/McSim/hello HELLO
