# #_threads=0  trace_file  dir
0 /home/cumulus/mcsim/TraceGen/mcf.trace /home/cumulus/mcsim/McSim/hello HELLO
0 /home/cumulus/mcsim/TraceGen/mcf.trace /home/cumulus/mcsim/McSim/hello HELLO
0 /home/cumulus/mcsim/TraceGen/mcf.trace /home/cumulus/mcsim/McSim/hello HELLO
0 /home/cumulus/mcsim/TraceGen/mcf.trace /home/cumulus/mcsim/McSim/hello HELLO
0 /home/cumulus/mcsim/TraceGen/mcf.trace /home/cumulus/mcsim/McSim/hello HELLO
0 /home/cumulus/mcsim/TraceGen/mcf.trace /home/cumulus/mcsim/McSim/hello HELLO
0 /home/cumulus/mcsim/TraceGen/mcf.trace /home/cumulus/mcsim/McSim/hello HELLO
0 /home/cumulus/mcsim/TraceGen/mcf.trace /home/cumulus/mcsim/McSim/hello HELLO
0 /home/cumulus/mcsim/TraceGen/mcf.trace /home/cumulus/mcsim/McSim/hello HELLO
0 /home/cumulus/mcsim/TraceGen/mcf.trace /home/cumulus/mcsim/McSim/hello HELLO
